### ISSUE TITLE
path adding issue 

### ISSUE THREAD

**Issue by rvweeren** [rvweeren/lofar_facet_selfcal#14]
https://github.com/rvweeren/lofar_facet_selfcal/blob/a34db2ad4ccafdfc749fbb678983cac930f5d3e3/facetselfcal.py#L4280

This line produces the following error:

```
Traceback (most recent call last):
  File "/tmp/facetselfcal.py", line 4721, in <module>
    main()
  File "/tmp/facetselfcal.py", line 4280, in main
    sys.path.append(os.path.abspath(args['helperscriptspathh5merge']))
  File "/opt/lofar/pyenv-py2/lib64/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/opt/lofar/pyenv-py2/lib64/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by rvweeren** [comment]
Could this be caused when helperscriptspathh5merge is not set by the user?
